var dataArray = [ 
    {
        name:"Black Sketchers",
        description: "Bought these new sketchers, didn't like them as much as I thought. Worn a couple of times, but in good shape.", 
        imgSrc:"https://www.skechers.ca/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwe58888c7/images/large/232040_BBK.jpg?sw=1120", 
        buyNow: 156, 
        topBid: 130, 
        time: "10 days", 
        id: 1, 
        category: "Apparel",
        subCategory: "Shoes"
    },
    {
        name:"2023 Hyundai Sonata",
        description:"Brand new 2023 Hyundai Sonata, has only been driven from the dealership to my house, 33km on it total. Dark grey and still has that new car smell", 
        imgSrc:"https://s7d1.scene7.com/is/image/hyundai/2022-sonata-1?wid=1200&hei=630&qlt=85,0&fmt=webp", 
        buyNow: 25000, 
        topBid: 20000, 
        time: "5 days", 
        id: 2,
        category: "Vehicles",
        subCategory: "Cars"
    },
    {
        name:"Black Sketchers",
        description: "Bought these new sketchers, didn't like them as much as I thought. Worn a couple of times, but in good shape.", 
        imgSrc:"https://www.skechers.ca/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwe58888c7/images/large/232040_BBK.jpg?sw=1120", 
        buyNow: 156, 
        topBid: 130, 
        time: "10 days", 
        id: 3, 
        category: "Apparel",
        subCategory: "Shoes"
    },
    {
        name:"Black Sketchers",
        description: "Bought these new sketchers, didn't like them as much as I thought. Worn a couple of times, but in good shape.", 
        imgSrc:"https://www.skechers.ca/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwe58888c7/images/large/232040_BBK.jpg?sw=1120", 
        buyNow: 156, 
        topBid: 130, 
        time: "10 days", 
        id: 1, 
        category: "Apparel",
        subCategory: "Shoes"
    },
    {
        name:"Black Sketchers",
        description: "Bought these new sketchers, didn't like them as much as I thought. Worn a couple of times, but in good shape.", 
        imgSrc:"https://www.skechers.ca/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwe58888c7/images/large/232040_BBK.jpg?sw=1120", 
        buyNow: 156, 
        topBid: 130, 
        time: "10 days", 
        id: 1, 
        category: "Apparel",
        subCategory: "Shoes"
    },
    {
        name:"Black Sketchers",
        description: "Bought these new sketchers, didn't like them as much as I thought. Worn a couple of times, but in good shape.", 
        imgSrc:"https://www.skechers.ca/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwe58888c7/images/large/232040_BBK.jpg?sw=1120", 
        buyNow: 156, 
        topBid: 130, 
        time: "10 days", 
        id: 1, 
        category: "Apparel",
        subCategory: "Shoes"
    },
    {
        name:"AMG GT 63",
        description:"You have long since overtaken the mainstream. Demonstrate your claim to leadership with the new Mercedes-AMG GT 4-door coupés: Uncompromising performance, first-class road capability and as individual as you are.", 
        imgSrc:"https://www.motortrend.com/uploads/2022/06/2022-Mercedes-AMG-GT63-004-1.jpg", 
        buyNow: 1780, 
        topBid: 1430, 
        time: "", 
        id: 2,
        category: 1,
        subCategory: 2
    },
    {
        name:"Black Sketchers",
        description: "Bought these new sketchers, didn't like them as much as I thought. Worn a couple of times, but in good shape.", 
        imgSrc:"https://www.skechers.ca/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwe58888c7/images/large/232040_BBK.jpg?sw=1120", 
        buyNow: 156, 
        topBid: 130, 
        time: "10 days", 
        id: 1, 
        category: "Apparel",
        subCategory: "Shoes"
    },
    {
        name:"Black Sketchers",
        description: "Bought these new sketchers, didn't like them as much as I thought. Worn a couple of times, but in good shape.", 
        imgSrc:"https://www.skechers.ca/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwe58888c7/images/large/232040_BBK.jpg?sw=1120", 
        buyNow: 156, 
        topBid: 130, 
        time: "10 days", 
        id: 1, 
        category: "Apparel",
        subCategory: "Shoes"
    },
    {
        name:"Black Sketchers",
        description: "Bought these new sketchers, didn't like them as much as I thought. Worn a couple of times, but in good shape.", 
        imgSrc:"https://www.skechers.ca/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwe58888c7/images/large/232040_BBK.jpg?sw=1120", 
        buyNow: 156, 
        topBid: 130, 
        time: "10 days", 
        id: 1, 
        category: "Apparel",
        subCategory: "Shoes"
    },
    {
        name:"Black Sketchers",
        description: "Bought these new sketchers, didn't like them as much as I thought. Worn a couple of times, but in good shape.", 
        imgSrc:"https://www.skechers.ca/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwe58888c7/images/large/232040_BBK.jpg?sw=1120", 
        buyNow: 156, 
        topBid: 130, 
        time: "10 days", 
        id: 1, 
        category: "Apparel",
        subCategory: "Shoes"
    },
    {
        name:"AMG GT 63",
        description:"You have long since overtaken the mainstream. Demonstrate your claim to leadership with the new Mercedes-AMG GT 4-door coupés: Uncompromising performance, first-class road capability and as individual as you are.", 
        imgSrc:"https://www.motortrend.com/uploads/2022/06/2022-Mercedes-AMG-GT63-004-1.jpg", 
        buyNow: 1780, 
        topBid: 1430, 
        time: "", 
        id: 2,
        category: 1,
        subCategory: 2
    },
    {
        name:"Black Sketchers",
        description: "Bought these new sketchers, didn't like them as much as I thought. Worn a couple of times, but in good shape.", 
        imgSrc:"https://www.skechers.ca/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwe58888c7/images/large/232040_BBK.jpg?sw=1120", 
        buyNow: 156, 
        topBid: 130, 
        time: "10 days", 
        id: 1, 
        category: "Apparel",
        subCategory: "Shoes"
    },
    {
        name:"Black Sketchers",
        description: "Bought these new sketchers, didn't like them as much as I thought. Worn a couple of times, but in good shape.", 
        imgSrc:"https://www.skechers.ca/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwe58888c7/images/large/232040_BBK.jpg?sw=1120", 
        buyNow: 156, 
        topBid: 130, 
        time: "10 days", 
        id: 1, 
        category: "Apparel",
        subCategory: "Shoes"
    },
    {
        name:"Black Sketchers",
        description: "Bought these new sketchers, didn't like them as much as I thought. Worn a couple of times, but in good shape.", 
        imgSrc:"https://www.skechers.ca/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwe58888c7/images/large/232040_BBK.jpg?sw=1120", 
        buyNow: 156, 
        topBid: 130, 
        time: "10 days", 
        id: 1, 
        category: "Apparel",
        subCategory: "Shoes"
    },
    {
        name:"Black Sketchers",
        description: "Bought these new sketchers, didn't like them as much as I thought. Worn a couple of times, but in good shape.", 
        imgSrc:"https://www.skechers.ca/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwe58888c7/images/large/232040_BBK.jpg?sw=1120", 
        buyNow: 156, 
        topBid: 130, 
        time: "10 days", 
        id: 1, 
        category: "Apparel",
        subCategory: "Shoes"
    },
    {
        name:"AMG GT 63",
        description:"You have long since overtaken the mainstream. Demonstrate your claim to leadership with the new Mercedes-AMG GT 4-door coupés: Uncompromising performance, first-class road capability and as individual as you are.", 
        imgSrc:"https://www.motortrend.com/uploads/2022/06/2022-Mercedes-AMG-GT63-004-1.jpg", 
        buyNow: 1780, 
        topBid: 1430, 
        time: "", 
        id: 2,
        category: 1,
        subCategory: 2
    },
    {
        name:"Black Sketchers",
        description: "Bought these new sketchers, didn't like them as much as I thought. Worn a couple of times, but in good shape.", 
        imgSrc:"https://www.skechers.ca/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwe58888c7/images/large/232040_BBK.jpg?sw=1120", 
        buyNow: 156, 
        topBid: 130, 
        time: "10 days", 
        id: 1, 
        category: "Apparel",
        subCategory: "Shoes"
    },
    {
        name:"Black Sketchers",
        description: "Bought these new sketchers, didn't like them as much as I thought. Worn a couple of times, but in good shape.", 
        imgSrc:"https://www.skechers.ca/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwe58888c7/images/large/232040_BBK.jpg?sw=1120", 
        buyNow: 156, 
        topBid: 130, 
        time: "10 days", 
        id: 1, 
        category: "Apparel",
        subCategory: "Shoes"
    },
    {
        name:"Black Sketchers",
        description: "Bought these new sketchers, didn't like them as much as I thought. Worn a couple of times, but in good shape.", 
        imgSrc:"https://www.skechers.ca/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwe58888c7/images/large/232040_BBK.jpg?sw=1120", 
        buyNow: 156, 
        topBid: 130, 
        time: "10 days", 
        id: 1, 
        category: "Apparel",
        subCategory: "Shoes"
    },
    {
        name:"Black Sketchers",
        description: "Bought these new sketchers, didn't like them as much as I thought. Worn a couple of times, but in good shape.", 
        imgSrc:"https://www.skechers.ca/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwe58888c7/images/large/232040_BBK.jpg?sw=1120", 
        buyNow: 156, 
        topBid: 130, 
        time: "10 days", 
        id: 1, 
        category: "Apparel",
        subCategory: "Shoes"
    },
    {
        name:"AMG GT 63",
        description:"You have long since overtaken the mainstream. Demonstrate your claim to leadership with the new Mercedes-AMG GT 4-door coupés: Uncompromising performance, first-class road capability and as individual as you are.", 
        imgSrc:"https://www.motortrend.com/uploads/2022/06/2022-Mercedes-AMG-GT63-004-1.jpg", 
        buyNow: 1780, 
        topBid: 1430, 
        time: "", 
        id: 2,
        category: 1,
        subCategory: 2
    },
    {
        name:"Black Sketchers",
        description: "Bought these new sketchers, didn't like them as much as I thought. Worn a couple of times, but in good shape.", 
        imgSrc:"https://www.skechers.ca/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwe58888c7/images/large/232040_BBK.jpg?sw=1120", 
        buyNow: 156, 
        topBid: 130, 
        time: "10 days", 
        id: 1, 
        category: "Apparel",
        subCategory: "Shoes"
    },
    {
        name:"Black Sketchers",
        description: "Bought these new sketchers, didn't like them as much as I thought. Worn a couple of times, but in good shape.", 
        imgSrc:"https://www.skechers.ca/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwe58888c7/images/large/232040_BBK.jpg?sw=1120", 
        buyNow: 156, 
        topBid: 130, 
        time: "10 days", 
        id: 1, 
        category: "Apparel",
        subCategory: "Shoes"
    },
    {
        name:"Black Sketchers",
        description: "Bought these new sketchers, didn't like them as much as I thought. Worn a couple of times, but in good shape.", 
        imgSrc:"https://www.skechers.ca/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwe58888c7/images/large/232040_BBK.jpg?sw=1120", 
        buyNow: 156, 
        topBid: 130, 
        time: "10 days", 
        id: 1, 
        category: "Apparel",
        subCategory: "Shoes"
    },
    {
        name:"Black Sketchers",
        description: "Bought these new sketchers, didn't like them as much as I thought. Worn a couple of times, but in good shape.", 
        imgSrc:"https://www.skechers.ca/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwe58888c7/images/large/232040_BBK.jpg?sw=1120", 
        buyNow: 156, 
        topBid: 130, 
        time: "10 days", 
        id: 1, 
        category: "Apparel",
        subCategory: "Shoes"
    },
    {
        name:"AMG GT 63",
        description:"You have long since overtaken the mainstream. Demonstrate your claim to leadership with the new Mercedes-AMG GT 4-door coupés: Uncompromising performance, first-class road capability and as individual as you are.", 
        imgSrc:"https://www.motortrend.com/uploads/2022/06/2022-Mercedes-AMG-GT63-004-1.jpg", 
        buyNow: 1780, 
        topBid: 1430, 
        time: "", 
        id: 2,
        category: 1,
        subCategory: 2
    },
    {
        name:"Black Sketchers",
        description: "Bought these new sketchers, didn't like them as much as I thought. Worn a couple of times, but in good shape.", 
        imgSrc:"https://www.skechers.ca/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwe58888c7/images/large/232040_BBK.jpg?sw=1120", 
        buyNow: 156, 
        topBid: 130, 
        time: "10 days", 
        id: 1, 
        category: "Apparel",
        subCategory: "Shoes"
    },
    {
        name:"Black Sketchers",
        description: "Bought these new sketchers, didn't like them as much as I thought. Worn a couple of times, but in good shape.", 
        imgSrc:"https://www.skechers.ca/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwe58888c7/images/large/232040_BBK.jpg?sw=1120", 
        buyNow: 156, 
        topBid: 130, 
        time: "10 days", 
        id: 1, 
        category: "Apparel",
        subCategory: "Shoes"
    },
    {
        name:"Black Sketchers",
        description: "Bought these new sketchers, didn't like them as much as I thought. Worn a couple of times, but in good shape.", 
        imgSrc:"https://www.skechers.ca/dw/image/v2/BDCN_PRD/on/demandware.static/-/Sites-skechers-master/default/dwe58888c7/images/large/232040_BBK.jpg?sw=1120", 
        buyNow: 156, 
        topBid: 130, 
        time: "10 days", 
        id: 1, 
        category: "Apparel",
        subCategory: "Shoes"
    },
]



